-- Initial schema baseline.
-- Captures the current JPA entity definitions:
--   * com.spring.<projectName>.user.entity.User           → "user" (quoted; user is a PG reserved word)
--   * com.spring.<projectName>.verify.entity.EmailVerifier → email_verifier
-- Common audit columns come from BaseEntity (created_at, updated_at, deleted_at).
-- Existing dev/prod RDS instances skip V1 via spring.flyway.baseline-on-migrate=true;
-- only empty DBs (e.g. local fresh start) execute this script.

CREATE TABLE "user" (
    user_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(255) NOT NULL,
    password     VARCHAR(255) NOT NULL,
    user_role    INTEGER      NOT NULL,
    provider     VARCHAR(255),
    provider_id  VARCHAR(255),
    date_joined  TIMESTAMPTZ  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    deleted_at   TIMESTAMPTZ
);

CREATE TABLE email_verifier (
    email_verifier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255) NOT NULL,
    code              VARCHAR(255),
    token             VARCHAR(255) NOT NULL,
    purpose           VARCHAR(255),
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    deleted_at        TIMESTAMPTZ
);
